name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi:

flutter:
  uses-material-design: true
